[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
bus = { path = "../bus" }
logging = { path = "../logging" }
sdl3 = { version = "0.18.4", features = ["build-from-source-static", "image", "unsafe_textures"] }
send_wrapper = "0.6.0"
buffer_rw = { path = "../../buffer_rw" }

[dev-dependencies]
platform = { path = "../platform" }
