package bones:core@0.1.0;

interface host-api {
    enum level {
        debug,
        info,
        warn,
        error,
    }

    log: func(level: level, message: string);
    subscribe: func(topic: string);
    publish: func(topic: string, payload: list<u8>);
}

world extension {
    import host-api;

    export init: func();
    export on-tick: func(dt: f32);
    export on-message: func(topic: string, sender: string, payload: list<u8>);
}
