[package]
name = "bones-module-game-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bones-kernel = { path = "../bones-kernel", default-features = false }
bones-messages = { path = "../../bones-messages" }
hecs = "0.10"
rapier2d = "0.22"
glam = "0.30"
tiled = "0.16"
