//! Host-side bindings for the `bones:core` WIT package. Generated by
//! wasmtime's `bindgen!` macro; kept as a thin wrapper so `wasm_extensions` never
//! invokes the macro itself.

wasmtime::component::bindgen!({
    path: "../../../wit",
    world: "extension",
});

#[cfg(test)]
mod tests {
    use super::*;
    use bones::core::host_api::{Host, Level};

    #[test]
    fn generated_bindings_expose_the_extension_world_and_level_enum() {
        let _ = Level::Debug;
        let _ = Level::Info;
        let _ = Level::Warn;
        let _ = Level::Error;
        fn _assert_world_type_exists(_: &Extension) {}
        fn _assert_host_import_trait_exists<T: Host>() {}
    }
}
