[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bus = { path = "../bus" }
logging = { path = "../logging" }
renderer = { path = "../renderer" }
bones-messages = { path = "../../shared/bones-messages" }
egui = "0.32"
sdl3 = { version = "0.18.4", features = ["build-from-source-static", "unsafe_textures"] }

[dev-dependencies]
platform = { path = "../platform" }
