[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
bus = { path = "../bus" }
host = { path = "../host" }
logging = { path = "../logging" }
platform = { path = "../platform" }
wasmtime = { version = "46.0.1", features = ["component-model"] }

[dev-dependencies]
sdl3 = { version = "0.18.4", features = ["build-from-source-static"] }
